/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) mit_convex_centroidal_dyn_disc_phi_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s1[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s2[4] = {0, 1, 0, 0};
static const casadi_int casadi_s3[44] = {25, 13, 0, 2, 4, 6, 11, 16, 21, 22, 23, 24, 25, 26, 27, 28, 12, 15, 13, 16, 14, 17, 0, 3, 6, 9, 15, 1, 4, 7, 10, 16, 2, 5, 8, 11, 17, 18, 19, 20, 21, 22, 23, 24};
static const casadi_int casadi_s4[28] = {25, 25, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

/* mit_convex_centroidal_dyn_disc_phi_fun_jac_hess:(i0[13],i1[12],i2[13],i3[0])->(o0[13],o1[25x13,28nz],o2[25x25,0nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6;
  a0=arg[0]? arg[0][0] : 0;
  a1=2.0000000000000000e-02;
  a2=arg[0]? arg[0][3] : 0;
  a3=(a1*a2);
  a0=(a0+a3);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][1] : 0;
  a3=arg[0]? arg[0][4] : 0;
  a4=(a1*a3);
  a0=(a0+a4);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[0]? arg[0][2] : 0;
  a4=arg[0]? arg[0][5] : 0;
  a5=(a1*a4);
  a0=(a0+a5);
  if (res[0]!=0) res[0][2]=a0;
  a0=1.6640319494134288e-03;
  a5=arg[1]? arg[1][0] : 0;
  a5=(a0*a5);
  a6=arg[1]? arg[1][3] : 0;
  a6=(a0*a6);
  a5=(a5+a6);
  a6=arg[1]? arg[1][6] : 0;
  a6=(a0*a6);
  a5=(a5+a6);
  a6=arg[1]? arg[1][9] : 0;
  a6=(a0*a6);
  a5=(a5+a6);
  a2=(a2+a5);
  if (res[0]!=0) res[0][3]=a2;
  a2=arg[1]? arg[1][1] : 0;
  a2=(a0*a2);
  a5=arg[1]? arg[1][4] : 0;
  a5=(a0*a5);
  a2=(a2+a5);
  a5=arg[1]? arg[1][7] : 0;
  a5=(a0*a5);
  a2=(a2+a5);
  a5=arg[1]? arg[1][10] : 0;
  a5=(a0*a5);
  a2=(a2+a5);
  a3=(a3+a2);
  if (res[0]!=0) res[0][4]=a3;
  a3=arg[1]? arg[1][2] : 0;
  a3=(a0*a3);
  a2=arg[1]? arg[1][5] : 0;
  a2=(a0*a2);
  a3=(a3+a2);
  a2=arg[1]? arg[1][8] : 0;
  a2=(a0*a2);
  a3=(a3+a2);
  a2=arg[1]? arg[1][11] : 0;
  a2=(a0*a2);
  a3=(a3+a2);
  a4=(a4+a3);
  if (res[0]!=0) res[0][5]=a4;
  a4=arg[0]? arg[0][6] : 0;
  if (res[0]!=0) res[0][6]=a4;
  a4=arg[0]? arg[0][7] : 0;
  if (res[0]!=0) res[0][7]=a4;
  a4=arg[0]? arg[0][8] : 0;
  if (res[0]!=0) res[0][8]=a4;
  a4=arg[0]? arg[0][9] : 0;
  if (res[0]!=0) res[0][9]=a4;
  a4=arg[0]? arg[0][10] : 0;
  if (res[0]!=0) res[0][10]=a4;
  a4=arg[0]? arg[0][11] : 0;
  if (res[0]!=0) res[0][11]=a4;
  a4=arg[0]? arg[0][12] : 0;
  if (res[0]!=0) res[0][12]=a4;
  a4=1.;
  if (res[1]!=0) res[1][0]=a4;
  if (res[1]!=0) res[1][1]=a1;
  if (res[1]!=0) res[1][2]=a4;
  if (res[1]!=0) res[1][3]=a1;
  if (res[1]!=0) res[1][4]=a4;
  if (res[1]!=0) res[1][5]=a1;
  if (res[1]!=0) res[1][6]=a0;
  if (res[1]!=0) res[1][7]=a0;
  if (res[1]!=0) res[1][8]=a0;
  if (res[1]!=0) res[1][9]=a0;
  if (res[1]!=0) res[1][10]=a4;
  if (res[1]!=0) res[1][11]=a0;
  if (res[1]!=0) res[1][12]=a0;
  if (res[1]!=0) res[1][13]=a0;
  if (res[1]!=0) res[1][14]=a0;
  if (res[1]!=0) res[1][15]=a4;
  if (res[1]!=0) res[1][16]=a0;
  if (res[1]!=0) res[1][17]=a0;
  if (res[1]!=0) res[1][18]=a0;
  if (res[1]!=0) res[1][19]=a0;
  if (res[1]!=0) res[1][20]=a4;
  if (res[1]!=0) res[1][21]=a4;
  if (res[1]!=0) res[1][22]=a4;
  if (res[1]!=0) res[1][23]=a4;
  if (res[1]!=0) res[1][24]=a4;
  if (res[1]!=0) res[1][25]=a4;
  if (res[1]!=0) res[1][26]=a4;
  if (res[1]!=0) res[1][27]=a4;
  return 0;
}

CASADI_SYMBOL_EXPORT int mit_convex_centroidal_dyn_disc_phi_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mit_convex_centroidal_dyn_disc_phi_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mit_convex_centroidal_dyn_disc_phi_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mit_convex_centroidal_dyn_disc_phi_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mit_convex_centroidal_dyn_disc_phi_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mit_convex_centroidal_dyn_disc_phi_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mit_convex_centroidal_dyn_disc_phi_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void mit_convex_centroidal_dyn_disc_phi_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mit_convex_centroidal_dyn_disc_phi_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int mit_convex_centroidal_dyn_disc_phi_fun_jac_hess_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real mit_convex_centroidal_dyn_disc_phi_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mit_convex_centroidal_dyn_disc_phi_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mit_convex_centroidal_dyn_disc_phi_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mit_convex_centroidal_dyn_disc_phi_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mit_convex_centroidal_dyn_disc_phi_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s3;
    case 2: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mit_convex_centroidal_dyn_disc_phi_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int mit_convex_centroidal_dyn_disc_phi_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
